# Generated by Django 5.0.2 on 2024-03-01 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApiApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
